repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        name: mypy
        always_run: true
        additional_dependencies: [pydantic>=2.3.4]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        name: ruff-check
        always_run: true
        args: [--fix]
      - id: ruff-format
        name: ruff-format
        always_run: true
