name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  ci:
    uses: community-of-python/community-workflow/.github/workflows/preset_with_just.yml@main
    secrets: inherit
